endpoint: 'wss://bsr.zeitgeist.pm:443'
mock-signature-host: true
block: 2604527
db: ./batterystation.kusama.db.sqlite
import-storage:
  System:
    Account:
      - - - dDyymrYQMxP5ksYCLXQjv9oAYiQdJFE9Ampgv8cYxc4qXpTNH
        - data:
            free: 300000002999993
  Sudo:
    Key: dDyymrYQMxP5ksYCLXQjv9oAYiQdJFE9Ampgv8cYxc4qXpTNH
  Council:
    Members:
      - dE1fLRenofs4ss5vmbYkA861qoSXFjTWW6wQXwT5qE7EoL18h
      - dE31LET4U4bUu8GZd9XjvWS4PSyL6kawHmL11o9gtHvrTfCU2
      - dE3vHqCTMjjUbirNRTZd7ioECnAFrPS8qN3CXPs3dg4ZEDu7z
      - dE48WzqUfLrhNxUpcA7mLEPFvzNZV1NS2L6N5mgQnLMUPq4xi
      - dE4W3DbggVyrVAqMqGfwWWGHL6gxfCdsiyVynzsnYcMsf7uq7
